name: Build and Deploy Crud-App-Master

on:
  push:
    branches:
      - 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Run SonarQube scan
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # 3. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 4. Login to Amazon ECR
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 5. Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          docker build -t simple-nodejs-app:$IMAGE_TAG .
          docker tag simple-nodejs-app:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/crud-app:$IMAGE_TAG
          docker tag simple-nodejs-app:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/crud-app:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/crud-app:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/crud-app:latest

      # 6. Register new ECS task definition revision
      - name: Register ECS Task Definition
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          TASK_DEF_JSON=$(aws ecs describe-task-definition --task-definition crud-app-task)
          NEW_TASK_DEF=$(echo $TASK_DEF_JSON | jq 'del(.taskDefinition.taskDefinitionArn, .taskDefinition.revision, .taskDefinition.status, .taskDefinition.requiresAttributes, .taskDefinition.compatibilities, .taskDefinition.registeredAt, .taskDefinition.registeredBy)')
          NEW_TASK_DEF=$(echo $NEW_TASK_DEF | jq --arg IMAGE "${{ steps.login-ecr.outputs.registry }}/simple-nodejs-app:$IMAGE_TAG" '.taskDefinition.containerDefinitions[0].image=$IMAGE')
          echo $NEW_TASK_DEF | jq '.taskDefinition' > new-task-def.json
          aws ecs register-task-definition --cli-input-json file://new-task-def.json

      # 7. Update ECS service
      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.CLUSTER_NAME }} \
            --service ${{ secrets.SERVICE_NAME }} \
            --force-new-deployment
